spring:
  profiles:
    active: loadInitialData
  datasource:
    url: "jdbc:h2:mem:testdb"
    driver-class-name: "org.h2.Driver"
    username: "sa"
    password: "password"
  h2:
    console:
      enabled: true
  mail:
    host: "sandbox.smtp.mailtrap.io"
    port: 2525
    username: "7f293e84c72ac5"
    password: "27d8f43da5b152"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true